export const jobs = [
    {
      id: 1,
      title: 'Junior Engineer',
      position: 'Junior Engineer',
      description: 'Responsible for assisting senior engineers in various civil engineering projects.',
      qualification: 'Diploma in Civil Engineering',
      location: 'New Delhi',
      salary: '₹35,000 - ₹50,000 per month',
      applyLink: '/apply/junior-engineer',
      postedDate: '2024-09-15',
      lastDateToApply: '2024-10-05',
      category: 'Engineering',
      experience: '1-2 years of relevant experience',
      organization: 'Public Works Department',
    },
    {
      id: 2,
      title: 'Clerk',
      position: 'Clerk',
      description: 'Assist in office tasks, file management, and clerical duties in a government office.',
      qualification: '12th Pass',
      location: 'Mumbai',
      salary: '₹20,000 - ₹25,000 per month',
      applyLink: '/apply/clerk',
      postedDate: '2024-09-10',
      lastDateToApply: '2024-09-30',
      category: 'Administrative',
      experience: 'No experience required',
      organization: 'Ministry of Home Affairs',
    },
    {
      id: 3,
      title: 'Accountant',
      position: 'Accountant',
      description: 'Manage financial transactions, prepare financial reports, and maintain records.',
      qualification: 'B.Com or equivalent',
      location: 'Bangalore',
      salary: '₹40,000 - ₹55,000 per month',
      applyLink: '/apply/accountant',
      postedDate: '2024-09-18',
      lastDateToApply: '2024-10-10',
      category: 'Finance',
      experience: '2+ years of experience in accounting',
      organization: 'State Finance Department',
    },
    {
      id: 4,
      title: 'IBPS PO',
      position: 'Probationary Officer',
      description: 'Work as a probationary officer in public sector banks, handling various banking operations.',
      qualification: 'Graduate in any discipline',
      location: 'Pan India',
      salary: '₹52,000 per month',
      applyLink: '/apply/ibps-po',
      postedDate: '2024-09-12',
      lastDateToApply: '2024-09-28',
      category: 'Banking',
      experience: 'No prior experience required',
      organization: 'Institute of Banking Personnel Selection (IBPS)',
    }
  ];
  